### ISSUE TITLE
Output all small case?

### ISSUE THREAD

**Issue by maxcribe** [RobertRiachi/ANE-Optimized-Whisper-OpenAI#1]
Just had some time to test it, great work! It indeed is a lot faster than whisper on m1 macs. 

One thing I noticed is, while whisper command line run gives you an output with correct work capitalizations, this one prints out everything in small case. Also the ANE output seems to be missing some punctuations here and there

**output from vanilla whisper:**

The following is a conversation with Yann LeCun, his second time in the podcast. He is the Chief AI Scientist at Meta, formerly Facebook, professor at NYU, touring award winner, one of the seminal figures in the history of machine learning and artificial intelligence, and someone who is brilliant and opinionated in the best kind of way, and so is always fun to talk to. This is the Lex Friedman podcast, to support it, please check out our sponsors in the description, and now, here's my conversation with Yann LeCun. 

**output from ANE:** 

the following is a conversation with yann lecun, his second time in the podcast. he is the chief ai scientist at meta, formerly facebook, professor at nyu, touring award winner, one of the seminal figures in the history of machine learning and artificial intelligence, and someone who is brilliant and opinionated in the best kind of way, and so it was always fun to talk to. this is the lex freeman podcast. to support it, please check out our sponsors in the description, and now here's my conversation, with yann lecun.

**Comment by RobertRiachi** [comment]
That's strange, I just validated that prior to exporting to CoreML both the original OpenAI Whisper (from [github](https://github.com/openai/whisper)) and WhisperANE both produce identical results albeit they both appear to output all lowercase?

Also just to clarify which Whisper are you using to produce the first output, and are you comparing it to WhisperANE before or after you exported it to CoreML? These specifics might help us get to the bottom of things :)

Finally I also just pushed some conversion code for exporting to coreml since I realized that was missing.

**Comment by maxcribe** [comment]
Hi, I am using the Whisper installed from master on github. The first output is whisper being run from command line, the second from the code in this repo. 

> are you comparing it to WhisperANE before or after you exported it to CoreML? 

not sure what this question means but I am simply passing a file in the test script and getting the output. Both whisper outputs i copied above are completely independent of each other

**Comment by wangchou** [comment]
@maxcribe 
It's because of calling ```lower()``` in test script
https://github.com/RobertRiachi/ANE-Optimized-Whisper-OpenAI/blob/d42252155b8e29b2e2c32e7b911ec647198547fb/test_transcribe.py#L17
